name:    project
version: 0.1.0.0

dependencies:
- base >= 4.7 && < 5
- array
- mtl

library:
  source-dirs: src
  build-tools:
  - alex == 3.2.*
  - happy == 1.20.*

executable:
  main: Main.hs
  source-dirs: app
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  dependencies:
  - project
  - repline == 0.4.*

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - project
    - directory
    - filepath
    - hspec
